name: Deploy Sample App to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: ms-apimsample   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: b2c
    steps:
    - uses: actions/checkout@v3
    - name: build it
      run: |
        npm install --loglevel verbose
        npm run build --verbose
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: sample-app
        path: b2c/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: b2c
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: sample-app
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}